---
- name: create ec2 instance
  ec2:
    image: "{{ ami_image }}"
    instance_type: "{{ instance_type }}"
    region: ap-northeast-1
    key_name: "{{ key_name }}"
    group: "{{ group_name }}"
    instance_tags:
      Name: "{{ group_name }}"
    wait: yes
    wait_timeout: 300
    volumes:
      - device_name: "{{ device_name }}"
        device_type: "{{ device_type }}"
        volume_size: "{{ volume_size }}"
        delete_on_termination: yes
  register: ec2
 
- name: waiting until accessable with ssh
  pause: minutes=5
 
- name: add created instance to inventory
  add_host: hostname="host_{{ group_name }}"
            ansible_ssh_host="{{ item.public_ip }}"
            ansible_ssh_user=ec2-user
            ansible_ssh_private_key_file="~/.ssh/CloudConductor.pem"
  with_items: ec2.instances