- name: セキュリティグループを作成
  ec2_group:
    name: "{{ group_name }}"
    description: "{{ group_name }} server security group"
    region: ap-northeast-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0